projects=gradle-build-operations,gradle-concurrent,gradle-files,gradle-hashing,gradle-io,gradle-java-language-extensions,gradle-serialization,gradle-time
runtime=commons-io-2.15.1.jar,commons-lang-2.6.jar,failureaccess-1.0.1.jar,minlog-1.2.jar,objenesis-2.6.jar
